# aca podemos hacer directo una peticion http con el cursor lo llevamos donde dice SEND REQUEST y el nos da una response 


### Get Orders

GET http://localhost:4004/odata/v4/manage-orders/GetOrders 

### Get Orders  aca estamos filtrando por email 
GET http://localhost:4004/odata/v4/manage-orders/GetOrders('client1@client1.com') 

### Create Order
POST http://localhost:4004/odata/v4/manage-orders/CreateOrder HTTP/1.1
Content-Type: application/json

{
    "ClientEmail": "carlosreyes@gmail.com",
    "FirstName": "carlos",
    "LastName": "reyes",
    "CreatedOn": "2023-10-10",
    "Reviewed": true,
    "Approved": true,
    "Country_code": "ES",
    "Status": null
}